default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: "(^migrations/|/migrations/|^tests/|/tests/)"
      - id: trailing-whitespace
        exclude: "(^migrations/|/migrations/|^tests/|/tests/)"

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        exclude: "(^migrations/|/migrations/|^tests/|/tests/)"
        args: ["--profile", "black"]
  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ["--in-place" ,"--remove-all-unused-imports", "--ignore-init-module-imports" ]
        exclude: "(^migrations/|/migrations/|^tests/|/tests/)"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args: [
          "--line-length", "79",
          "--no-fix",
          "--select", "ALL",
          "--extend-ignore",
          "E902,D100,D101,D102,D103,D104,D105,D106,D107,S106,S104,FAST002,ANN201,PTH123,FA102,FA100,COM812,I001,Q000,UP006,RUF022,EXE002,UP035,FBT003,FBT001,ANN204,FIX002,TD003,TD002,B008",
        ]
        exclude: "(^migrations/|/migrations/|^tests/|/tests/)"
        files: "^(main\\.py)$"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [ "--severity", "high", "--recursive" ]
        exclude: "(^migrations/|/migrations/|^tests/|/tests/)"
        files: "^(main\\.py)$"

  - repo: local
    hooks:
      - id: sonar-scanner
        name: SonarQube Scanner (staged files only)
        entry: ./run_scanner.sh
        language: system
        pass_filenames: false
